import asyncio
import time
import mysql.connector

from websocket import create_connection

greeting = {}

# async def hello():
#     async with websockets.connect('ws://livestats.proxy.lolesports.com/stats?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjoiMS4wIiwiamlkIjoiODMyMjNmZjMtYmJjOS00ZWIyLWI5ZWQtMDViYjZkNjg5OGYxIiwiaWF0IjoxNDU0NzQxNTA5MjcxLCJleHAiOjE0NTUzNDYzMDkyNzEsIm5iZiI6MTQ1NDc0MTUwOTI3MSwiY2lkIjoiYTkyNjQwZjI2ZGMzZTM1NGI0MDIwMjZhMjA3NWNiZjMiLCJzdWIiOnsiaXAiOiI2Ni4yMTkuMjM2LjE3MyIsInVhIjoiTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV09XNjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS80OC4wLjI1NjQuOTcgU2FmYXJpLzUzNy4zNiJ9LCJyZWYiOlsid2F0Y2guKi5sb2xlc3BvcnRzLmNvbSJdLCJzcnYiOlsibGl2ZXN0YXRzLXYxLjAiXX0.S435BFidWXuaHjwglUVWo1-bO46hVXMhq1IBWX1tzyE') as websocket:
#
#         greeting = await websocket.recv()
#
# loop = asyncio.get_event_loop()
# loop.run_until_complete(hello())
# loop.close()
#
#
# print(hello())

#Token api location: http://api.lolesports.com/api/issueToken

ws = create_connection("ws://livestats.proxy.lolesports.com/stats?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjoiMS4wIiwiamlkIjoiODMyMjNmZjMtYmJjOS00ZWIyLWI5ZWQtMDViYjZkNjg5OGYxIiwiaWF0IjoxNDU0NzQxNTA5MjcxLCJleHAiOjE0NTUzNDYzMDkyNzEsIm5iZiI6MTQ1NDc0MTUwOTI3MSwiY2lkIjoiYTkyNjQwZjI2ZGMzZTM1NGI0MDIwMjZhMjA3NWNiZjMiLCJzdWIiOnsiaXAiOiI2Ni4yMTkuMjM2LjE3MyIsInVhIjoiTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV09XNjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS80OC4wLjI1NjQuOTcgU2FmYXJpLzUzNy4zNiJ9LCJyZWYiOlsid2F0Y2guKi5sb2xlc3BvcnRzLmNvbSJdLCJzcnYiOlsibGl2ZXN0YXRzLXYxLjAiXX0.S435BFidWXuaHjwglUVWo1-bO46hVXMhq1IBWX1tzyE")
# ws = websockets.connect('ws://livestats.proxy.lolesports.com/stats?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjoiMS4wIiwiamlkIjoiODMyMjNmZjMtYmJjOS00ZWIyLWI5ZWQtMDViYjZkNjg5OGYxIiwiaWF0IjoxNDU0NzQxNTA5MjcxLCJleHAiOjE0NTUzNDYzMDkyNzEsIm5iZiI6MTQ1NDc0MTUwOTI3MSwiY2lkIjoiYTkyNjQwZjI2ZGMzZTM1NGI0MDIwMjZhMjA3NWNiZjMiLCJzdWIiOnsiaXAiOiI2Ni4yMTkuMjM2LjE3MyIsInVhIjoiTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV09XNjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS80OC4wLjI1NjQuOTcgU2FmYXJpLzUzNy4zNiJ9LCJyZWYiOlsid2F0Y2guKi5sb2xlc3BvcnRzLmNvbSJdLCJzcnYiOlsibGl2ZXN0YXRzLXYxLjAiXX0.S435BFidWXuaHjwglUVWo1-bO46hVXMhq1IBWX1tzyE')
for x in range (0,20):
    greeting = ws.recv()
    time.sleep(1)
    print(greeting)

ws.close()
